#!/bin/bash
# RLD System Orchestrator with New PostgreSQL Indexer
# One command to launch the entire simulation environment with the new indexer
# Usage: ./scripts/orchestrator_new_indexer.sh

set -e
RLD_ROOT="/home/ubuntu/RLD"
INDEXER_ROOT="/home/ubuntu/RLD-indexing/indexer"
cd "$RLD_ROOT"

source scripts/utils/colors.sh

log_header "RLD SYSTEM ORCHESTRATOR (with PostgreSQL Indexer)"

# ═══════════════════════════════════════════════════════════════
# PHASE 1: CLEANUP & CHAIN
# ═══════════════════════════════════════════════════════════════
log_phase "1" "INFRASTRUCTURE"
scripts/infra/kill_all.sh

# Also stop any running PostgreSQL indexer
pkill -f "python -m src.main" 2>/dev/null || true
docker stop rld-indexer-db 2>/dev/null || true

scripts/infra/start_anvil.sh

# ═══════════════════════════════════════════════════════════════
# PHASE 2: DEPLOY (Updates .env automatically)
# ═══════════════════════════════════════════════════════════════
log_phase "2" "DEPLOY PROTOCOL & MARKET"
scripts/infra/deploy_protocol.sh
scripts/infra/deploy_market.sh

# Reload .env with new addresses
source /home/ubuntu/RLD/.env

# ═══════════════════════════════════════════════════════════════
# PHASE 3: START POSTGRESQL INDEXER
# ═══════════════════════════════════════════════════════════════
log_phase "3" "START POSTGRESQL INDEXER"

# Start PostgreSQL via Docker
cd "$INDEXER_ROOT"
docker-compose up -d postgres
sleep 3  # Wait for DB to be ready

# Create .env for indexer
cat > .env <<EOF
# Auto-generated by orchestrator
DB_HOST=localhost
DB_PORT=5432
DB_USER=rld
DB_PASSWORD=rld_dev_password
DB_NAME=rld_indexer

RPC_URL=$RPC_URL
CHAIN_ID=${CHAIN_ID:-1}
START_BLOCK=0
FINALITY_BLOCKS=1

RLD_CORE_ADDRESS=$RLD_CORE
BROKER_FACTORY_ADDRESS=$BROKER_FACTORY

READ_ONLY_MODE=true
DUAL_SOURCE_MODE=true
RECONCILE_BLOCKS=10
LOG_LEVEL=INFO
EOF

# Install dependencies if needed
if [ ! -d ".venv" ]; then
    log_step "3.1" "Installing Python dependencies..."
    python3 -m venv .venv
    source .venv/bin/activate
    pip install -q -r requirements.txt
else
    source .venv/bin/activate
fi

# Start the indexer
log_step "3.2" "Starting PostgreSQL indexer..."
python -m src.main --mode indexer > /tmp/pg_indexer.log 2>&1 &
echo $! > /tmp/pg_indexer.pid

log_success "PostgreSQL Indexer started (PID: $(cat /tmp/pg_indexer.pid))"
echo "   Log: /tmp/pg_indexer.log"
echo "   DB:  postgresql://rld@localhost:5432/rld_indexer"

cd "$RLD_ROOT"

# ═══════════════════════════════════════════════════════════════
# PHASE 4: SETUP USERS
# ═══════════════════════════════════════════════════════════════
log_phase "4" "SETUP USERS"

# Reload .env after deploy
source /home/ubuntu/RLD/.env

# User A: LP Provider ($100M collateral, $5M LP)
scripts/scenarios/lp_provider.sh "$USER_A_KEY" 100000000 5000000

# Reload to get USER_A_BROKER
source /home/ubuntu/RLD/.env

# User B: Go Long ($100k)
scripts/scenarios/long_user.sh "$USER_B_KEY" 100000

# User C: TWAMM Order ($100k, 1 hour)
scripts/scenarios/twamm_user.sh "$USER_C_KEY" 100000 1

# MM Bot ($10M)
scripts/scenarios/mm_bot.sh "$MM_KEY" 10000000

# Chaos Trader ($10M)
scripts/scenarios/chaos_trader.sh "$CHAOS_KEY" 10000000

# ═══════════════════════════════════════════════════════════════
# PHASE 5: START DAEMONS
# ═══════════════════════════════════════════════════════════════
log_phase "5" "START DAEMONS"

# Reload to get all broker addresses
source /home/ubuntu/RLD/.env

scripts/infra/start_daemons.sh
scripts/infra/start_chaos.sh

# ═══════════════════════════════════════════════════════════════
# PHASE 6: START API SERVER (optional)
# ═══════════════════════════════════════════════════════════════
log_phase "6" "START INDEXER API"

cd "$INDEXER_ROOT"
source .venv/bin/activate
python -m src.main --mode api > /tmp/pg_indexer_api.log 2>&1 &
echo $! > /tmp/pg_indexer_api.pid

log_success "Indexer API started (PID: $(cat /tmp/pg_indexer_api.pid))"
echo "   API: http://localhost:8080/api/v1/status"
echo "   Log: /tmp/pg_indexer_api.log"

cd "$RLD_ROOT"

# ═══════════════════════════════════════════════════════════════
# SUMMARY
# ═══════════════════════════════════════════════════════════════
echo ""
log_header "SYSTEM READY (New Indexer)"
echo ""
echo "  📊 PG Indexer: Running (PID: $(cat /tmp/pg_indexer.pid 2>/dev/null || echo 'N/A'))"
echo "  🌐 API:        Running (PID: $(cat /tmp/pg_indexer_api.pid 2>/dev/null || echo 'N/A'))"
echo "  🤖 Daemon:     Running (PID: $(cat /tmp/daemon.pid 2>/dev/null || echo 'N/A'))"
echo "  🌀 Chaos:      Running (PID: $(pgrep -f chaos_daemon.py 2>/dev/null || echo 'N/A'))"
echo "  ⛓️  Anvil:      Running (PID: $(cat /tmp/anvil.pid 2>/dev/null || echo 'N/A'))"
echo "  🐘 PostgreSQL: Running (Docker: rld-indexer-db)"
echo ""
echo "  Endpoints:"
echo "    API Status: http://localhost:8080/api/v1/status"
echo "    Brokers:    http://localhost:8080/api/v1/brokers/{address}"
echo "    Markets:    http://localhost:8080/api/v1/markets/{market_id}"
echo ""
echo "  Logs:"
echo "    /tmp/anvil.log"
echo "    /tmp/pg_indexer.log"
echo "    /tmp/pg_indexer_api.log"
echo "    /tmp/daemon.log"
echo "    /tmp/chaos_trader.log"
echo ""
echo "  Config: /home/ubuntu/RLD/.env"
echo ""

